<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateListDocumentTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('list_document', function (Blueprint $table) {
            $table->increments('id');
            $table->string('id_regis')->reference('id_pasien')->on('identifikasi');
            $table->boolean('rj_asesmen_awal_perawat')->default(False);
            $table->boolean('rj_asesmen_awal_dokter')->default(False);
            $table->boolean('rj_asesmen_awal_gigi_perawat')->default(False);
            $table->boolean('rj_asesmen_awal_gigi_dokter')->default(False);
            $table->boolean('rj_informasi_edukasi')->default(False);
            $table->boolean('rj_lapor_rehabilitasi')->default(False);
            $table->boolean('rj_identifikasi_stresor')->default(False);
            $table->boolean('rj_tes_konseling_hiv')->default(False);
            $table->boolean('rj_izin_vct_hiv')->default(False);
            $table->boolean('rj_hiv_anti_retroval')->default(False);
            $table->boolean('rj_perkembangan_pasien')->default(False);
            $table->boolean('rj_asesmen_awal_tumbuh_kembang_psikolog')->default(False);
            $table->boolean('rj_asesmen_awal_tumbuh_kembang_dokter')->default(False);
            $table->boolean('rj_asesmen_awal_tumbuh_kembang_psikiatri')->default(False);
            $table->boolean('rj_resume')->default(False);
            $table->boolean('igd_triase')->default(False);
            $table->boolean('igd_asesmen_awal_rawat_darurat_perawat')->default(False);
            $table->boolean('igd_asesmen_awal_rawat_darurat_dokter')->default(False);
            $table->boolean('igd_suicide_fisik')->default(False);
            $table->boolean('igd_catatan_kemajuan')->default(False);
            $table->boolean('igd_catatan_perkembangan')->default(False);
            $table->boolean('ri_surat_persetujuan')->default(False);
            $table->boolean('ri_resume_medis')->default(False);
            $table->boolean('ri_dpjp_case')->default(False);
            $table->boolean('ri_persetujuan_umum')->default(False);
            $table->boolean('ri_hak_kewajiban')->default(False);
            $table->boolean('ri_asesmen')->default(False);
            $table->boolean('ri_suicide_fisik')->default(False);
            $table->boolean('ri_asesmen_awal_keperawatan_napza')->default(False);
            $table->boolean('ri_penilaian_edmunson')->default(False);
            $table->boolean('ri_risiko_nyeri')->default(False);
            $table->boolean('ri_catatan_perkembangan')->default(False);
            $table->boolean('ri_keperawatan_intensif')->default(False);
            $table->boolean('ri_evaluasi_keperawatan')->default(False);
            $table->boolean('ri_monitoring_observasi')->default(False);
            $table->boolean('ri_laboratorium')->default(False);
            $table->boolean('ri_rencana_napza')->default(False);
            $table->boolean('ri_penggunaan_obat')->default(False);
            $table->boolean('ri_riwayat_obat')->default(False);
            $table->boolean('ri_efek_samping')->default(False);
            $table->boolean('ri_asuhan_gizi')->default(False);
            $table->boolean('ri_edukasi')->default(False);
            $table->boolean('ri_rencana_pemulangan')->default(False);
            $table->boolean('ri_panss_ec')->default(False);
            $table->boolean('ri_penilaian_panss')->default(False);
            $table->boolean('ri_lembar_konsultasi')->default(False);
            $table->boolean('ri_transfer_internal')->default(False);
            $table->boolean('ri_transfer_eksternal')->default(False);
            $table->boolean('ri_pemberian_informasi')->default(False);
            $table->boolean('ri_pemeriksaan_psikologis')->default(False);
            $table->boolean('ri_serah_terima')->default(False);
            $table->boolean('ri_surat_spd')->default(False);
            $table->boolean('ri_permintaan_privasi')->default(False);
            $table->boolean('ri_permintaan_rohani')->default(False);
            $table->boolean('ri_permintaan_second')->default(False);
            $table->boolean('ri_do_not_resucitate')->default(False);
            $table->boolean('ri_instruksi_do_not_resucitate')->default(False);
            $table->boolean('ri_persetujuan_tindakan')->default(False);
            $table->boolean('ri_penolakan_tindakan')->default(False);
            $table->boolean('ri_pulang_paksa')->default(False);
            $table->boolean('ri_residen')->default(False);
            $table->boolean('ri_surat_kuasa')->default(False);
            $table->boolean('ri_pernyataan')->default(False);

            $table->string('rj_asesmen_awal_perawat_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_dokter_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_perawat_date',50)->nullable();
            $table->string('rj_asesmen_awal_dokter_date',50)->nullable();
            $table->string('rj_asesmen_awal_gigi_perawat_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_gigi_dokter_petugas',50)->nullable();
            $table->string('rj_informasi_edukasi_petugas',50)->nullable();
            $table->string('rj_lapor_rehabilitasi_petugas',50)->nullable();
            $table->string('rj_identifikasi_stresor_petugas',50)->nullable();
            $table->string('rj_tes_konseling_hiv_petugas',50)->nullable();
            $table->string('rj_izin_vct_hiv_petugas',50)->nullable();
            $table->string('rj_hiv_anti_retroval_petugas',50)->nullable();
            $table->string('rj_perkembangan_pasien_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_tumbuh_kembang_psikolog_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_tumbuh_kembang_dokter_petugas',50)->nullable();
            $table->string('rj_asesmen_awal_tumbuh_kembang_psikiatri_petugas',50)->nullable();
            $table->string('rj_resume_petugas',50)->nullable();
            $table->string('igd_triase_petugas',50)->nullable();
            $table->string('igd_asesmen_awal_rawat_darurat_perawat_petugas',50)->nullable();
            $table->string('igd_asesmen_awal_rawat_darurat_dokter_petugas',50)->nullable();
            $table->string('igd_suicide_fisik_petugas',50)->nullable();
            $table->string('igd_catatan_kemajuan_petugas',50)->nullable();
            $table->string('igd_catatan_perkembangan_petugas',50)->nullable();
            $table->string('ri_surat_persetujuan_petugas',50)->nullable();
            $table->string('ri_resume_medis_petugas',50)->nullable();
            $table->string('ri_dpjp_case_petugas',50)->nullable();
            $table->string('ri_persetujuan_umum_petugas',50)->nullable();
            $table->string('ri_hak_kewajiban_petugas',50)->nullable();
            $table->string('ri_asesmen_petugas',50)->nullable();
            $table->string('ri_suicide_fisik_petugas',50)->nullable();
            $table->string('ri_asesmen_awal_keperawatan_napza_petugas',50)->nullable();
            $table->string('ri_penilaian_edmunson_petugas',50)->nullable();
            $table->string('ri_risiko_nyeri_petugas',50)->nullable();
            $table->string('ri_catatan_perkembangan_petugas',50)->nullable();
            $table->string('ri_keperawatan_intensif_petugas',50)->nullable();
            $table->string('ri_evaluasi_keperawatan_petugas',50)->nullable();
            $table->string('ri_monitoring_observasi_petugas',50)->nullable();
            $table->string('ri_laboratorium_petugas',50)->nullable();
            $table->string('ri_rencana_napza_petugas',50)->nullable();
            $table->string('ri_penggunaan_obat_petugas',50)->nullable();
            $table->string('ri_riwayat_obat_petugas',50)->nullable();
            $table->string('ri_efek_samping_petugas',50)->nullable();
            $table->string('ri_asuhan_gizi_petugas',50)->nullable();
            $table->string('ri_edukasi_petugas',50)->nullable();
            $table->string('ri_rencana_pemulangan_petugas',50)->nullable();
            $table->string('ri_panss_ec_petugas',50)->nullable();
            $table->string('ri_penilaian_panss_petugas',50)->nullable();
            $table->string('ri_lembar_konsultasi_petugas',50)->nullable();
            $table->string('ri_transfer_internal_petugas',50)->nullable();
            $table->string('ri_transfer_eksternal_petugas',50)->nullable();
            $table->string('ri_pemberian_informasi_petugas',50)->nullable();
            $table->string('ri_pemeriksaan_psikologis_petugas',50)->nullable();
            $table->string('ri_serah_terima_petugas',50)->nullable();
            $table->string('ri_surat_spd_petugas',50)->nullable();
            $table->string('ri_permintaan_privasi_petugas',50)->nullable();
            $table->string('ri_permintaan_rohani_petugas',50)->nullable();
            $table->string('ri_permintaan_second_petugas',50)->nullable();
            $table->string('ri_do_not_resucitate_petugas',50)->nullable();
            $table->string('ri_instruksi_do_not_resucitate_petugas',50)->nullable();
            $table->string('ri_persetujuan_tindakan_petugas',50)->nullable();
            $table->string('ri_penolakan_tindakan_petugas',50)->nullable();
            $table->string('ri_pulang_paksa_petugas',50)->nullable();
            $table->string('ri_residen_petugas',50)->nullable();
            $table->string('ri_surat_kuasa_petugas',50)->nullable();
            $table->string('ri_pernyataan_petugas',50)->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('list_document');
    }
}
