<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateRiAsuhanGiziTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ri_asuhan_gizi', function (Blueprint $table) {
            $table->increments('id');
            $table->string('id_regis')->reference('id_pasien')->on('identifikasi');
            $table->string('umur')->nullable();
            $table->string('etnik_agama')->nullable();
            $table->string('jenis_kelamin')->nullable();
            $table->string('kemampuan_baca',1)->nullable();
            $table->string('pekerjaan')->nullable();
            $table->string('pendidikan')->nullable();
            $table->string('peran_dalam_keluarga')->nullable();
            $table->string('keterbatasan_fisik')->nullable();
            $table->string('mobilitas')->nullable();
            $table->string('perokok',1)->nullable();
            $table->string('riwayat')->nullable();
            $table->string('diagnosa_dokter')->nullable();
            $table->string('alergi_makanan')->nullable();
            $table->string('ketidaksukaan_makanan')->nullable();
            $table->string('pantangan_makanan')->nullable();
            $table->string('konseling_sebelumnya',1)->nullable();
            $table->string('keterangan_konseling')->nullable();
            $table->string('bb_saat_ini')->nullable();
            $table->string('pbtb')->nullable();
            $table->string('imt')->nullable();
            $table->string('status_gizi')->nullable();
            $table->string('bb_biasanya')->nullable();
            $table->string('penurunan_bb')->nullable();
            $table->string('penurunan_bb_adj')->nullable();
            $table->string('pengukuran_lainnya')->nullable();
            $table->string('biokimia_terkait')->nullable();
            $table->string('fk1',1)->nullable();
            $table->string('fk2',1)->nullable();
            $table->string('fk3',1)->nullable();
            $table->string('fk4',1)->nullable();
            $table->string('fk5',1)->nullable();
            $table->string('fk6',1)->nullable();
            $table->string('fk7',1)->nullable();
            $table->string('fk8',1)->nullable();
            $table->string('fk9',1)->nullable();
            $table->string('fk10')->nullable();
            $table->string('fk11')->nullable();
            $table->string('fk12')->nullable();
            $table->string('fk13',1)->nullable();
            $table->string('fk14',1)->nullable();
            $table->string('fk15',1)->nullable();
            $table->string('fk16')->nullable();
            $table->string('fk17')->nullable();
            $table->string('fk18')->nullable();
            $table->string('fk19')->nullable();
            $table->string('diagnosa_gizi')->nullable();
            $table->string('tujuan_intervensi')->nullable();
            $table->string('target_intervensi')->nullable();
            $table->string('rencana_monitoring_evaluasi')->nullable();
            $table->string('p_gr_nasi',30)->nullable();
            $table->string('p_urt_nasi',30)->nullable();
            $table->string('p_gr_lauk',30)->nullable();
            $table->string('p_urt_lauk',30)->nullable();
            $table->string('p_gr_sayur',30)->nullable();
            $table->string('p_urt_sayur',30)->nullable();
            $table->string('p_nama_snack',30)->nullable();
            $table->string('p_gr_snack',30)->nullable();
            $table->string('p_urt_snack',30)->nullable();
            $table->string('energi_pagi',30)->nullable();
            $table->string('protein_pagi',30)->nullable();
            $table->string('lemak_pagi',30)->nullable();
            $table->string('kh_pagi',30)->nullable();
            $table->string('s_gr_nasi',30)->nullable();
            $table->string('s_urt_nasi',30)->nullable();
            $table->string('s_gr_lauk',30)->nullable();
            $table->string('s_urt_lauk',30)->nullable();
            $table->string('s_gr_tempe',30)->nullable();
            $table->string('s_urt_tempe',30)->nullable();
            $table->string('s_gr_sayur',30)->nullable();
            $table->string('s_urt_sayur',30)->nullable();
            $table->string('s_gr_buah',30)->nullable();
            $table->string('s_urt_buah',30)->nullable();
            $table->string('s_nama_snack',30)->nullable();
            $table->string('s_gr_snack',30)->nullable();
            $table->string('s_urt_snack',30)->nullable();
            $table->string('energi_siang',30)->nullable();
            $table->string('protein_siang',30)->nullable();
            $table->string('lemak_siang',30)->nullable();
            $table->string('kh_siang',30)->nullable();
            $table->string('m_gr_nasi',30)->nullable();
            $table->string('m_urt_nasi',30)->nullable();
            $table->string('m_gr_lauk',30)->nullable();
            $table->string('m_urt_lauk',30)->nullable();
            $table->string('m_gr_tempe',30)->nullable();
            $table->string('m_urt_tempe',30)->nullable();
            $table->string('m_gr_sayur',30)->nullable();
            $table->string('m_urt_sayur',30)->nullable();
            $table->string('m_gr_buah',30)->nullable();
            $table->string('m_urt_buah',30)->nullable();
            $table->string('m_nama_snack',30)->nullable();
            $table->string('m_gr_snack',30)->nullable();
            $table->string('m_urt_snack',30)->nullable();
            $table->string('energi_malam',30)->nullable();
            $table->string('protein_malam',30)->nullable();
            $table->string('lemak_malam',30)->nullable();
            $table->string('kh_malam',30)->nullable();
            $table->string('jumlah_1',20)->nullable();
            $table->string('jumlah_2',20)->nullable();
            $table->string('jumlah_3',20)->nullable();
            $table->string('jumlah_4',20)->nullable();
            $table->string('jumlah_5',20)->nullable();
            $table->string('jumlah_6',20)->nullable();
            $table->string('jumlah_7',20)->nullable();
            $table->string('jumlah_8',20)->nullable();
            $table->string('jumlah_9',20)->nullable();
            $table->string('jumlah_10',20)->nullable();
            $table->string('jumlah_11',20)->nullable();
            $table->string('jumlah_12',20)->nullable();
            $table->string('jumlah_13',20)->nullable();
            $table->string('jumlah_14',20)->nullable();
            $table->string('jumlah_15',20)->nullable();
            $table->string('jumlah_16',20)->nullable();
            $table->string('jumlah_17',20)->nullable();
            $table->string('jumlah_18',20)->nullable();
            $table->string('jumlah_19',20)->nullable();
            $table->string('jumlah_20',20)->nullable();
            $table->string('jumlah_21',20)->nullable();
            $table->string('jumlah_22',20)->nullable();
            $table->string('jumlah_23',20)->nullable();
            $table->string('jumlah_24',20)->nullable();
            $table->string('jumlah_25',20)->nullable();
            $table->string('jumlah_26',20)->nullable();
            $table->string('jumlah_27',20)->nullable();
            $table->string('jumlah_28',20)->nullable();
            $table->string('jumlah_29',20)->nullable();
            $table->string('jumlah_30',20)->nullable();
            $table->string('jumlah_31',20)->nullable();
            $table->string('jumlah_32',20)->nullable();
            $table->string('jumlah_33',20)->nullable();
            $table->string('jumlah_34',20)->nullable();
            $table->string('jumlah_35',20)->nullable();
            $table->string('jumlah_36',20)->nullable();
            $table->string('jumlah_37',20)->nullable();
            $table->string('jumlah_38',20)->nullable();
            $table->string('jumlah_39',20)->nullable();
            $table->string('jumlah_40',20)->nullable();
            $table->string('jumlah_41',20)->nullable();
            $table->string('jumlah_42',20)->nullable();
            $table->string('jumlah_43',20)->nullable();
            $table->string('tanggal',10)->nullable();
            $table->string('jam',8)->nullable();
            $table->string('nama_ahli_gizi')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ri_asuhan_gizi');
    }
}
