<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RJAsesmenDokter extends Model
{
    protected $table = 'rj_asesmen_dokter';

    public $incrementing = true;

    public $timestamps = true;

    protected $fillable = [
        'id_regis',
		'pewawancara',
		'keluhan_utama',
		'riwayat_penyakit_sekarang',
		'riwayat_penyakit_dahulu',
		'riwayat_napza',
		'lama_pemakaian',
		'cara_pemakaian',
		'latar_belakang_pemakaian',
		'riwayat_pendidikan',
		'riwayat_pekerjaan',
		'riwayat_perkawinan',
		'riwayat_penyakit_lainnya',
		'riwayat_operasi',
		'jenis_operasi',
		'waktu_operasi',
		'riwayat_tranfusi',
		'reaksi_tranfusi',
		'reaksi_timbul',
		'riwayat_penyakit_dalam_keluarga',
		'riwayat_pengobatan',
		'riwayat_alergi',
		'kepala',
		'leher',
		'dada',
		'jantung',
		'paru',
		'perut',
		'anggota_gerak',
		'penampilan',
		'kesadaran_psikiatri',
		'orientasi',
		'sikap',
		'keterangan',
		'proses_pikir',
		'bentuk_pikir',
		'isi_pikir',
		'mood',
		'afek',
		'halusinasi',
		'ilusi',
		'konsentrasi',
		'ingat',
		'abstrak',
		'impuls',
		'nilai',
		'tilikan',
		'dipercaya',
		'meningeal',
		'nervus',
		'motorik',
		'cerebellum',
		'vegetatif',
		'gaduh_gelisah',
		'ketidakoperatifan',
		'permusuhan',
		'pengendalian_impuls',
		'ketegangan',
		'bangsal',
		'tanggal_pemeriksaan',
		'panss_ec',
		'gaff',
		'axis1',
		'axis2',
		'axis3',
		'axis4',
		'axis5',
		'utama',
		'sekunder',
		'jam',
		'tindakan_terapi',
		'daftar_masalah',
		'tindak_lanjut',
		'perlu_dikontrol',
		'tanggal_kontrol',
		'ruangan',
		'indikasi_rawat_inap',
		'alasan_menolak',
		'dirujuk_ke',
		'alasan_dirujuk',
		'kesadaran',
		'kesadaran_lainnya',
		'tensi',
		'nadi',
		'pernafasan',
		'suhu',
    ];
}
