<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RJTesKonselingHIV extends Model
{
    protected $table = 'rj_tes_konseling_hiv';

    public $incrementing = true;

    public $timestamps = true;

    protected $fillable = [
        'id_regis',
        'nama',
        'alamat',
        'propinsi',
        'kota_kabupaten',
        'nama_ibu_kandung',
        'jenis_kelamin',
        'spk',
        'tgl_lahir',
        'skh',
        'umur_anak_terakhir',
        'jumlah_anak_kandung',
        'pen',
        'pek',
        'jenis_pekerjaan',
        'kr',
        'ktr',
        'lama_ps_penasun',
        'sk',
        'sk',
        'sr',
        'pt',
        'pp',
        'ha',
        'tanggal_lahir_pasangan',
        'sp',
        'tgl_tes_terakhir_pasangan',
        'wbp',
        'tgl_konseling_pra_hiv',
        'skl',
        'alasan_tes',
        'dmn',
        'dmn_lainnya',
        'kaj',
        'waktu_kaj',
        'an',
        'waktu_an',
        'per',
        'waktu_per',
        'trf',
        'waktu_trf',
        'trm',
        'waktu_trm',
        'ktr_lainnya',
        'waktu_ktr_lainnya',
        'jd',
        'waktu_jd',
        'ksd',
        'tes_hiv',
        'tt_hiv',
        'wt_hiv',
        'ht_hiv',
        'tgl_pemberian_informasi',
        'tes_hiv2',
        'tt_hiv2',
        'wt_hiv2',
        'ht_hiv2',
        'ptp',
        'ims_lainnya',
        'ptp_lainnya',
        'kesediaan_tes_tipk',
        'tgl_tes_hiv',
        'jt',
        'r1',
        'r1_reagen',
        'r2',
        'r2_reagen',
        'r3',
        'r3_reagen',
        'kes',
        'nrn_pdp',
        'tgl_masuk_pdp',
        'tl_tipk',
        'shp',
        'tgl_konseling_pasca_tes',
        'tha',
        'ktb',
        'jkyd',
        'tl_kts',
        'rpp',
        'rpp_lsm',
        'ksl',
        'ksl_lainnya',
        'nama_konselor',
        'sl',
        'jpe',
    ];
}
